# Generated by Django 3.0.6 on 2020-05-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.CharField(max_length=10)),
                ('item_desc', models.TextField()),
                ('item_img', models.ImageField(upload_to='menu/static/img')),
            ],
        ),
    ]
